CREATE DATABASE doingsdone
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE projects (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(50) NOT NULL UNIQUE,
  id_user INT NOT NULL
);

CREATE TABLE tasks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(128) NOT NULL,
  date_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_complete TIMESTAMP NULL,
  completed BOOLEAN DEFAULT 0,
  deadline TIMESTAMP NULL,
  file CHAR(64),
  id_user INT NOT NULL,
  id_project INT NOT NULL,
  INDEX (name)
);

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(64) NOT NULL,
  date_register TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email CHAR(128) NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  INDEX (name)
);
